name: Linting

on:
  pull_request:
    branches:
      - 'develop'

jobs:
    Whitespaces:
        name: Check trailing whitespaces
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            - name: Install Ruff
              run: pip install ruff 
            - name: Trailing whitespaces
              run: ruff check --select=W291
            - name: Unused modules
              run: ruff check --select=F401